name: MLflow DockerHub CI

on:
  push:
    branches: [ main ]

jobs:
  train-build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Definisi Environment Variable untuk seluruh Job agar konsisten
    env:
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install mlflow scikit-learn pandas imbalanced-learn

    - name: Run Training MLProject
      run: |
        # Memastikan folder mlruns dibuat di root direktori
        mlflow run MLProject --env-manager local

    - name: Build Docker Image via MLflow
      run: |
        # 1. Verifikasi dan ambil Run ID dari folder MLProject
        if [ -f MLProject/run_id.txt ]; then
          RUN_ID=$(cat MLProject/run_id.txt)
          echo "Menggunakan Run ID: $RUN_ID"
        else
          echo "Error: MLProject/run_id.txt tidak ditemukan!"
          exit 1
        fi

        # 2. Jalankan build dengan mengarahkan ke local tracking URI
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/fraud-model-local:latest" \
          --env-manager local

    - name: Login & Push to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fraud-model-local:latest

    - name: Upload MLflow Logs to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-experiment-results
        path: |
          mlruns/
          MLProject/run_id.txt
